name: Track Price Every 2 Hours

on:
  schedule:
    - cron: "0 */2 * * *"  # This cron expression schedules the workflow to run every 2 hours
  workflow_dispatch:  # Allows manual trigger from the GitHub UI if needed

jobs:
  track-price:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python on the runner

      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies (if you have a requirements.txt file)

    - name: Run price tracking script
      run: |
        python app.py  # Replace with the path to your Python script
